# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars: 
  BIN_DIR: bin

tasks:
  fix:
    desc: Call go fix command
    cmds:
      - go fix ./...
    deps:
      - install
  
  build:
    desc: Build to binary file
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/main ./cmd/api/main.go
      - chmod +x {{.BIN_DIR}}/main

  run:
    desc: Run the application
    cmds:
      - ./{{.BIN_DIR}}/main
  
  clean:
    desc: Clean a binary file
    cmds:
      - rm -f {{.BIN_DIR}}/main

  install:
    desc: Checks for the presence of the utility
    cmds: 
      - |
        if !command -v go-task &> /dev/null; then
          go install github.com/go-task/task/v3/cmd/task@latest
        else
          echo "go-task exists"
        fi

  up:
    desc: Up docker-compose
    cmds:
      - docker-compose up -d
  
  down:
    desc: Down docker-compose
    cmds:
      - docker-compose down -v